module.exports = {
  defaults: {
    label: 'Выберите фильтр',
    class: 'dropdown-base',
    classButton: '',
    color: 'green',
    icon: {
      enabled: false,
      src: '/assets/images/user-icon.png',
      alt: 'icon',
    },
    buttons: [
      { title: '1/24', checked: true },
      { title: '1/48' },
      { title: '1/72' },
      { title: 'Нативный' },
      { title: '1/24' },
      { title: '1/48' },
      { title: '1/72' },
      { title: 'Нативный' },
    ],
    links: [
      { title: '1/24', href: "#" },
      { title: '1/48', href: "#" },
      { title: '1/72', href: "#" },
      { title: 'Нативный', href: "#" },
      { title: '1/24', href: "#" },
      { title: '1/48', href: "#" },
      { title: '1/72', href: "#" },
      { title: 'Нативный', href: "#" },
    ],
    checkboxes: [
      { title: 'Все', checked: true },
      { title: 'Банки' },
      { title: 'Банки' },
      { title: 'Автомобили' },  
    ],
    isPriority: false,
    isStatus: false,
    isCheckboxes: false,
    isButtons: false,
    isLinks: false,
  },
  mergeConfig(data, defaults) {
    return {
      label: data.label !== undefined ? data.label : defaults.label,
      class: data.class !== undefined ? data.class : defaults.class,
      classButton: data.classButton !== undefined ? data.classButton : defaults.classButton,
      color: data.color !== undefined ? data.color : defaults.color,
      icon: data.icon !== undefined ? data.icon.enabled : defaults.icon.enabled,
      src: data.icon !== undefined ? data.icon.src : defaults.src,
      alt: data.icon !== undefined ? data.icon.alt : defaults.alt,
      buttons: data.buttons !== undefined && data.buttons.length > 0 ? data.buttons : defaults.buttons,
      links: data.links !== undefined && data.links.length > 0 ? data.links : defaults.links,
      checkboxes: data.checkboxes !== undefined && data.checkboxes.length > 0 ? data.checkboxes : defaults.checkboxes,
      isPriority: data.isPriority !== undefined ? data.isPriority : defaults.isPriority,
      isStatus: data.isStatus !== undefined ? data.isStatus : defaults.isStatus,
      isCheckboxes: data.isCheckboxes !== undefined ? data.isCheckboxes : defaults.isCheckboxes,
      isButtons: data.isButtons !== undefined ? data.isButtons : defaults.isButtons,
      isLinks: data.isLinks !== undefined ? data.isLinks : defaults.isLinks,
    }
  }
}